name: clean_arc_bloc
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  graphql: ^5.1.1
  get_it: ^7.2.0
  cached_network_image: ^3.2.1
  drift: ^2.2.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.1
  connectivity_plus: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  drift_dev: ^2.2.0+1
  build_runner: ^2.2.1
  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/github.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48
flutter:
  uses-material-design: true
  fonts:
    - family: Merriweather
      fonts:
        - asset: asset/Merriweather/Merriweather-Regular.ttf
        - asset: asset/Merriweather/Merriweather-Italic.ttf
        - asset: asset/Merriweather/Merriweather-Black.ttf
        - asset: asset/Merriweather/Merriweather-Bold.ttf
        - asset: asset/Merriweather/Merriweather-Light.ttf
  assets:
    - asset/github.png
