name: clean_arc_bloc
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  graphql: ^5.1.1
  get_it: ^7.2.0
  cached_network_image: ^3.2.1
  drift: ^2.2.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.1
  connectivity_plus: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  drift_dev: ^2.2.0+1
  build_runner: ^2.2.1
flutter:
  uses-material-design: true
